const fs = require('fs');
const { JSDOM } = require('C:\\Users\\Administrator\\.workbuddy\\binaries\\node\\workspace\\node_modules\\jsdom');
const ROOT = 'C:\\Users\\Administrator\\WorkBuddy\\2026-08-12-16-19-26\\stark-steel-fresh';
let html = fs.readFileSync(ROOT + '/about.html', 'utf-8').replace(/<script[^>]*src=[^>]*><\/script>/g, '');
const dom = new JSDOM(html, { runScripts: 'dangerously', url: 'http://localhost/' });
const { window } = dom;
const s = window.document.createElement('script');
s.textContent = fs.readFileSync(ROOT + '/js/i18n.js', 'utf-8');
window.document.body.appendChild(s);
window.document.dispatchEvent(new window.Event('DOMContentLoaded'));
const v = window.document.querySelector('.company-video video source');
console.log('video source:', v ? v.getAttribute('src') : 'MISSING');
const h = window.document.querySelector('[data-i18n=companyVideoTitle]');
console.log('title en:', JSON.stringify(h.textContent.trim()));
window.StarkI18n.applyLang('zh');
console.log('title zh:', JSON.stringify(h.textContent.trim()));
window.StarkI18n.applyLang('ar');
console.log('title ar:', JSON.stringify(h.textContent.trim()));
const sub = window.document.querySelector('[data-i18n=companyVideoSub]');
window.StarkI18n.applyLang('es');
console.log('sub es  :', JSON.stringify(sub.textContent.trim()));
